// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY
using VkNet.Enums;

namespace VkNet.Utils
{
	public partial class VkResponse
	{
		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator DeleteFriendStatus(VkResponse response)
		{
			if (response == null || response[key: "success"] == 0)
			{
				return DeleteFriendStatus.Unknown;
			}

			if (response[key: "in_request_deleted"] != null && response[key: "in_request_deleted"] == 1
				|| response[key: "out_request_deleted"] != null && response[key: "out_request_deleted"] == 1)
			{
				return DeleteFriendStatus.RequestRejected;
			}

			if (response[key: "suggestion_deleted"] != null && response[key: "suggestion_deleted"] == 1)
			{
				return DeleteFriendStatus.RecommendationDeleted;
			}

			if (response[key: "friend_deleted"] != null && response[key: "friend_deleted"] == 1)
			{
				return DeleteFriendStatus.UserIsDeleted;
			}

			return DeleteFriendStatus.Unknown;
		}
	}
}