using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace VkNet.SourceGenerator
{
	[Generator]
	public class VkResponseToManualEnumCastsGenerator : ISourceGenerator
	{
		/// <inheritdoc />
		public void Initialize(GeneratorInitializationContext context)
		{
			context.RegisterForSyntaxNotifications(() => new VkResponseToManualEnumCastsReceiver());
		}

		/// <inheritdoc />
		public void Execute(GeneratorExecutionContext context)
		{
			if (context.SyntaxReceiver is not VkResponseToManualEnumCastsReceiver receiver)
			{
				return;
			}

			var sb = new StringBuilder();
			sb.AppendLine("// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY");
			sb.AppendLine();

			foreach (var usingName in receiver.CandidateUsingList)
			{
				sb.AppendLine($"using {usingName};");
			}

			sb.AppendLine();
			sb.AppendLine("namespace VkNet.Utils");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic partial class VkResponse");
			sb.AppendLine("\t{");

			foreach (var className in receiver.CandidateClasses.Distinct())
			{
				if (!receiver.DefaultValues.ContainsKey(className))
				{
					continue;
				}

				sb.AppendLine("\t\t/// <summary>");
				sb.AppendLine($"\t\t/// Преобразовать <see cref=\"{className}\" /> из <see cref=\"VkResponse\" />");
				sb.AppendLine("\t\t/// </summary>");
				sb.AppendLine("\t\t/// <param name=\"response\"> Ответ сервера vk.com. </param>");
				sb.AppendLine("\t\t/// <returns>");
				sb.AppendLine($"\t\t/// Результат преобразования в <see cref=\"{className}\" />.");
				sb.AppendLine("\t\t/// </returns>");
				sb.AppendLine($"\t\tpublic static implicit operator {className}(VkResponse response)");
				sb.AppendLine("\t\t{");

				sb.AppendLine(
					$"\t\t\treturn response == null ? {className}.{receiver.DefaultValues[className]} : Utilities.EnumFrom<{className}>(response);");

				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			context.AddSource($"{nameof(VkResponseToManualEnumCastsGenerator)}.g.cs",
				SourceText.From(sb.ToString(), Encoding.UTF8));
		}
	}
}